### ISSUE TITLE
easier example to find the binding

### ISSUE THREAD

**Issue by hakan42** [ghys/org.openhab.ui.iconset.climacons#1]
I cannot create a pull request against the Release notes, so I add it here:

you can run "grep" in the karaf console too:

    openhab> bundle:list  | grep -i clima
    222 | Active   |  80 | 2.0.0.201612131226    | Animated Climacons Iconset

This might easier thank scrolling through the complete list to find your icon set in the list of installed bundles

**Comment by ghys** [comment]
Thanks! I've included your tip to the new release's notes, so I'm closing this.
