### ISSUE TITLE
wrong animation in chrome after update

### ISSUE THREAD

**Issue by syscams** [ghys/org.openhab.ui.iconset.climacons#4]
there seems to be a bug fix in Chrome regarding the viewBox/transform-origin. 
Due this fix the origin for the animation is now wrong.

I solved the problem by adding (without beeing knowledgeable):

`transform-box: fill-box;`

e.g.

```
<svg
    version="1.1"
    id="sun"
    class="climacon climacon_sun"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    x="0px"
    y="0px"
    viewBox="15 15 70 70"
    enable-background="new 15 15 70 70"
    xml:space="preserve">
    <style type="text/css"><![CDATA[

        svg{
            shape-rendering: geometricPrecision
        }

        g, path, circle, rect{
        
            -webkit-transform-origin: 50% 50%;
            -moz-transform-origin: 50% 50%;
            -o-transform-origin: 50% 50%;
			transform-box: fill-box;
            transform-origin: 50% 50%;
...
```

**Comment by Orfait** [comment]
Same issue for me.
Where did you put the transform-box fix ?

**Comment by syscams** [comment]
I added it in all svg's inside the jar in the icons folder (I used 7-zip to open and edit the files)

            -o-transform-origin: 50% 50%;
	--->		transform-box: fill-box;
            transform-origin: 50% 50%;

**Comment by dmcwhinnie** [comment]
I created a pull request with the changes

https://github.com/ghys/org.openhab.ui.iconset.climacons/pull/5
